export const UI_TEXTS = {
	recentMatches: "Ostatnie mecze",
	gamesTogether: "Gry razem",
	level: "Poziom",
	ranking: "Ranking",
	toggleTheme: "Przełącz motyw",
	themeLight: "Jasny",
	themeDark: "Ciemny",
	themeSystem: "Systemowy",
	loading: "Loading...",
	loadingMatches: "Loading matches...",
	failedToLoadMatches: "Failed to load matches",
	networkError: "Network Error",
	unableToConnect: "Unable to connect to server",
	// Games Together
	commonGames: "Wspólne gry",
	wins: "Wygrane",
	losses: "Przegrane",
	topChampions: "Top championów",
	winrate: "Winrate",
	date: "Data",
	duration: "Czas trwania",
	result: "Wynik",
	win: "Wygrana",
	loss: "Przegrana",
	champion: "Champion",
	kda: "KDA",
	noCommonGames: "Brak wspólnych gier",
	previous: "Poprzednia",
	next: "Następna",
	games: "gier",
	blueTeam: "Niebiescy",
	redTeam: "Czerwoni",
	masteryLevel: "Poziom mastery",
	masteryPoints: "Punkty mastery",
	players: "Gracze",
	teams: "Drużyny",
	loadMore: "Załaduj więcej",
	scrollToTop: "Przewiń do góry",
	overallStats: "Podsumowanie",
	overallWinrate: "Ogólny Winrate",
	bestChampion: "Najlepsza postać",
	bestKDA: "Najlepsze KDA",
	mvp: "MVP",
} as const
